# Generated by Django 2.0.5 on 2018-06-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='two_fa_check',
            field=models.BooleanField(default=False),
        ),
    ]
