# Generated by Django 2.0.5 on 2018-06-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa_test', '0003_auto_20180620_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='SECKRET_KEY',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
