# Generated by Django 2.0.5 on 2018-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa_test', '0004_profile_seckret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='SECKRET_KEY',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
