# Generated by Django 2.0.5 on 2018-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa_test', '0005_auto_20180621_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_cofirmed',
            field=models.BooleanField(default=False),
        ),
    ]
