# Generated by Django 2.0.5 on 2018-06-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa_test', '0006_profile_email_cofirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='SECKRET_KEY',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
