# Generated by Django 2.0.5 on 2018-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa_test', '0007_auto_20180627_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_comfirm',
            field=models.BooleanField(default=False),
        ),
    ]
